index:
  pattern: /
  defaults:
    controller: Orders:index

add:
  pattern: /add
  defaults:
    controller: Orders:add

find:
  pattern: /find-item/{orderId}
  defaults:
    controller: Orders:findNewItem

edit:
  pattern: /edit/{orderId}
  defaults:
    controller: Orders:edit

remove:
  pattern: /remove/{orderId}
  defaults:
    controller: Orders:remove