index_page:
  pattern: -page-{page}
  defaults:
    page: 1
    controller: Events:index
  requirements:
    page: (\d+|all)

index:
  pattern: 
  defaults:
    page: 1  
    controller: Events:index

category_page:
  pattern: -{category}-page-{page}
  defaults:
    page: 1
    controller: Events:category
  requirements:
    page: (\d+|all)

category:
  pattern: -{category}
  defaults:
    controller: Events:category
