index:
  pattern: 
  defaults:
    controller: Shop:index


index_page: 
  pattern: -page-{page}
  defaults:
    page: 1
    controller: Shop:index
  requirements:
    page: (\d+|all)


category_page:
  pattern: -{category}-page-{page}
  defaults:
    page: 1
    controller: Shop:category
  requirements:
    page: (\d+|all)

category:
  pattern: -{category}
  defaults:
    controller: Shop:category