shop_dev:
  hosts:       needsandfun.dev
  namespace:   Needsandfun
  rewrite:     false
  paths:
    templates: needsandfun
    common:    needsandfun
  variables:
    DB_ENGINE: MYSQL
    MYSQL:  
      DB_USER: root
      DB_PASSWORD: 123qwe
      DB_HOST: 127.0.0.1    
      DB_NAME:   needsandfun
    TWIG:
      cache: /app/templates/cache/
    MAIL:
      host:       smtp.gmail.com
      port:       465
      encryption: ssl
      user:       noreply@weboshin.ru
      sender:     noreply@weboshin.ru
      reciever:   info@needsandfun.ru
      password:   1tp7mPcO90X_w3JZGrTo
    SOCIAL:
      twitter:   https://twitter.com/#!/NeedsAndFun 
      facebook: http://www.facebook.com/pages/%D0%9D%D1%83%D0%B6%D0%BD%D0%BE-%D0%B8-%D0%92%D0%B5%D1%81%D0%B5%D0%BB%D0%BE/337994872909310
      vkontakte:  http://vk.com/club35939180
    
shop_prod:
  hosts:       test.needsandfun.ru, needsandfun.ru, www.needsandfun.ru
  namespace:   Needsandfun
  rewrite:     false
  paths:
    templates: needsandfun
    common:    needsandfun
  variables:
    GOOGLE_ANALYTICS: UA-30150643-1
    DB_ENGINE: MYSQL
    MYSQL:  
      DB_USER: root
      DB_PASSWORD: 
      DB_HOST: 127.0.0.1  
      DB_NAME:   needf
    TWIG:
      cache: /app/templates/cache/
    MAIL:
      host:       smtp.gmail.com
      port:       465
      encryption: ssl
      user:       noreply@weboshin.ru
      sender:     noreply@weboshin.ru
      reciever:   info@needsandfun.ru
      password:   1tp7mPcO90X_w3JZGrTo
    SOCIAL:
      twitter:   https://twitter.com/#!/NeedsAndFun 
      facebook: http://www.facebook.com/pages/%D0%9D%D1%83%D0%B6%D0%BD%D0%BE-%D0%B8-%D0%92%D0%B5%D1%81%D0%B5%D0%BB%D0%BE/337994872909310
      vkontakte:  http://vk.com/club35939180
    
manager_dev:
  hosts:       needsandfun.dev
  namespace:   Managers
  rewrite:     false
  paths:
    templates: managers
    common:    managers
  variables:
    DB_ENGINE: MYSQL
    MYSQL:  
      DB_USER: root
      DB_PASSWORD: 123qwe
      DB_HOST: 127.0.0.1    
      DB_NAME:   needsandfun
    TWIG:
      cache: /app/templates/cache/    
    MAIL:
      host:       smtp.gmail.com
      port:       465
      encryption: ssl
      user:       noreply@weboshin.ru
      sender:     noreply@weboshin.ru
      reciever:   info@needsandfun.ru
      password:   1tp7mPcO90X_w3JZGrTo

manager_prod:
  hosts:       test.needsandfun.ru, needsandfun.ru, www.needsandfun.ru
  namespace:   Managers
  rewrite:     false
  paths:
    templates: managers
    common:    managers
  variables:
    DB_ENGINE: MYSQL
    MYSQL:
      DB_USER: needsandfun
      DB_PASSWORD: D5yY8erFgeSG
      DB_HOST: 127.0.0.1    
      DB_NAME:   needsandfun_prod
    TWIG:
      cache: /app/templates/cache/
    MAIL:
      host:       smtp.gmail.com
      port:       465
      encryption: ssl
      user:       noreply@weboshin.ru
      sender:     noreply@weboshin.ru
      reciever:   info@needsandfun.ru
      password:   1tp7mPcO90X_w3JZGrTo